# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -3.14159265359
    max_position: 3.14159265359
    has_velocity_limits: true
    max_velocity: 6.0057
    has_acceleration_limits: true
    max_acceleration: 6.1348
  joint2:
    has_position_limits: true
    min_position: -2.35619449019
    max_position: 2.35619449019
    has_velocity_limits: true
    max_velocity: 5.4105
    has_acceleration_limits: true
    max_acceleration: 1.8035
  joint3:
    has_position_limits: true
    min_position: -2.74016692563
    max_position: 2.74016692563
    has_velocity_limits: true
    max_velocity: 7.1558
    has_acceleration_limits: true
    max_acceleration: 4.2935
  joint4:
    has_position_limits: true
    min_position: -3.49065850399
    max_position: 3.49065850399
    has_velocity_limits: true
    max_velocity: 8.9274
    has_acceleration_limits: true
    max_acceleration: 18.7187
  joint5:
    has_position_limits: true
    min_position: -2.18166156499
    max_position: 2.18166156499
    has_velocity_limits: true
    max_velocity: 8.9274
    has_acceleration_limits: true
    max_acceleration: 21.5984
  joint6:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 17.4532
    has_acceleration_limits: true
    max_acceleration: 9.5993
