# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -3.14159265359
    max_position: 3.14159265359
    has_velocity_limits: true
    max_velocity: 3.5648
    has_acceleration_limits: true
    max_acceleration: 6.8795
  joint2:
    has_position_limits: true
    min_position: -1.74532925199
    max_position: 2.28638132011
    has_velocity_limits: true
    max_velocity: 3.5648
    has_acceleration_limits: true
    max_acceleration: 2.9114
  joint3:
    has_position_limits: true
    min_position: -2.80998009571
    max_position: 2.53072741539
    has_velocity_limits: true
    max_velocity: 3.9113
    has_acceleration_limits: true
    max_acceleration: 4.3312
  joint4:
    has_position_limits: true
    min_position: -4.71238898038
    max_position: 4.71238898038
    has_velocity_limits: true
    max_velocity: 6.2308
    has_acceleration_limits: true
    max_acceleration: 31.8712
  joint5:
    has_position_limits: true
    min_position: -2.53072741539
    max_position: 2.53072741539
    has_velocity_limits: true
    max_velocity: 6.8906
    has_acceleration_limits: true
    max_acceleration: 37.0221
  joint6:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 11.8438
    has_acceleration_limits: true
    max_acceleration: 22.2767
